In [1]:
amplitude = 5 
is_clipped = False
if amplitude > 3:
    print("clipping risk")

clipping risk


In [3]:
freq = 50
period = 1/freq
print(f"Period :  {period}seconds")


Period :  0.02seconds


```python
level = 42

if level > 50:
    print("A")
elif level > 30:
    print("B")
else:
    print("C")

for i in range(1, 6, 2):
    print(i)
```

#### B
#### 1
#### 3
#### 5

In [ ]:
for i in range(0,10,1):
    if i % 2 == 0 and i > 0 :
        print(i)


0
2
4
6
8


In [7]:
i = 0
while i < 5 :
    print("Sample index: ", i)
    i = i + 1

Sample index:  0
Sample index:  1
Sample index:  2
Sample index:  3
Sample index:  4


In [2]:
samples = [1,2,3,4,5]
for s in samples:
    print(s)

1
2
3
4
5


Hello world


In [3]:
signal = [3, 1, 4, 1, 5, 9, 2, 6]
print(signal[-3:])
signal.append(0)
print(signal[::-1])

[9, 2, 6]
[0, 6, 2, 9, 5, 1, 4, 1, 3]


In [4]:
a = [1,2,3]
b = a
b.append(4)
print(a)

[1, 2, 3, 4]


In [5]:
c = a[:]
c.append(7)
print(a)
print(c)

[1, 2, 3, 4]
[1, 2, 3, 4, 7]


In [ ]:
s = [4,1,7,3]
s.append(9)
print(s)
s.insert(0,100) #(index, values)
print(s)
s.pop() #last element popped
print(s)
s.pop(0) #index given
print(s)
s.remove(7) #value
print(s)
c = sorted(s) #copy returned, not in place
print(f"C : {c}")
print(s)
s.sort()
print(s)
s.reverse() #in place
s.extend([8,9,10])
print(s)
#s.something gula in place, jemon array.something in numpy inplace



[4, 1, 7, 3, 9]
[100, 4, 1, 7, 3, 9]
[100, 4, 1, 7, 3]
[4, 1, 7, 3]
[4, 1, 3]
C : [1, 3, 4]
[4, 1, 3]
[1, 3, 4]
[4, 3, 1, 8, 9, 10]


In [ ]:
squares = [x**2 for x in range(5)]
evens = [ x if x % 2 == 0 else 0 for x in range(5)] #if pore, if agey
clipped = [x if x < 5 else 5 for x in samples]
print(squares, evens, clipped)

[0, 1, 4, 9, 16] [0, 2, 4] [1, 2, 3, 4, 5]


new_list = [expression for item in iterable]
new_list = [expression for item in iterable if condition]

if condition: 
-This acts as a gatekeeper. The expression is only evaluated and added to the list if the condition evaluates to True.

This is where many beginners get tripped up. If you want to change the output based on a condition (rather than filtering items out entirely), the if-else block moves to the beginning of the comprehension, right inside the expression.

The Formula:
new_list = [expression_if_true if condition else expression_if_false for item in iterable]

In [11]:
def clip(samples, limit):
    for i in range(samples.size()):
        if samples[i] > limit:
            samples[i] = limit
        elif samples[i] < -limit and samples[i] != 0 :
            samples[i] = -limit
    return samples

In [14]:
signal = [1, -3, 5, -2, 0, 4, -1, 6, -5]
def job(signal):
    zercross = 0
    for i in range(1,len(signal)-1):
        if signal[i-1] * signal[i] < 0:
            zercross +=1 
    newlist = [abs(x) for x in signal if abs(x) > 2]
    print(f"Zero crossing count : {zercross}")
    print(f"New List : {newlist}")
job(signal)
     

Zero crossing count : 5
New List : [3, 5, 4, 6, 5]


In [1]:
s = "signal_01"
s.upper()

'SIGNAL_01'

In [2]:
s.lower()

'signal_01'

In [ ]:
s.split("_") #gives list of two string those that are separated by this delm

['signal', '01']

In [ ]:
"_".join(["a", "BangladeshCDI" , "Love of My life"]) #ekta word diye join kora

'a_BangladeshCDI_Love of My life'

In [ ]:
s.strip() #leading and trailing whitespace dur kora

'signal_01'

In [6]:
s.replace("signal", "noise") #s[index] diye kora jay na

'noise_01'

In [7]:
f"{s!r}"


"'signal_01'"

In [10]:
f"This is my pi: {3.1416:.2f}"

'This is my pi: 3.14'

In [ ]:
def normalize(samples, scale = 1.0, clip = True) :
    return samples, scale * 10, clip
a, b, c = normalize(10,1,False) #evabe tuple unpack kore brother
print(a,b,c)

10 10 False


In [ ]:
def combine(*varargs): #python e pass by reference bole kichu nei
    for s in varargs:
        print(s)
combine(1,2,3,4)

1
2
3
4


In [13]:
config = {"sample_rate": 8000, "channels": 2, "label": "sine"}

if("label" in config):
    print("eshan is gay")

eshan is gay


In [14]:
for s in config:
    print(s)

sample_rate
channels
label


In [15]:
for key,value in config.items():
    print(key, value)

sample_rate 8000
channels 2
label sine


In [17]:
samples = [1,2,3]

try:
    result = samples[10]
except IndexError as e:
    print("Out of bounds: ", e)
except ValueError as e:
    print("bad input")
finally :
    print("cleanup")


Out of bounds:  list index out of range
cleanup


In [18]:
def scale_signal(samples, factor=2, in_place=False):
    if in_place:
        for i in range(len(samples)):
            samples[i] *= factor
        return samples
    return [x * factor for x in samples]

data = [1, 2, 3]
result1 = scale_signal(data)
print(data, result1)

result2 = scale_signal(data, in_place=True)
print(data, result2)

def get_stats(d):
    d["calls"] = d.get("calls", 0) + 1
    return d

log = {}
get_stats(log)
get_stats(log)
print(log)

a, b, *c, d = (10, 20, 30, 40, 50)
print(a, b, c, d)

[1, 2, 3] [2, 4, 6]
[2, 4, 6] [2, 4, 6]
{'calls': 2}
10 20 [30, 40] 50


results=[] as a default argument. 
Python evaluates default arguments once, at function definition time — not on every call.
 
That list is created once and reused across every call that doesn't pass its own results.
Proof from the run: calling process([1,2,3], threshold=0) as a supposedly fresh call returns [100, 8, -9, 1, 2] — it's still holding state from the previous call. This is a classic Python trap, comes up constantly in interviews, and the fix is:
Never use a mutable object ([], {}, set()) as a default argument — use None and initialize inside.

In [5]:
def process(samples, threshold = 5,results = []):

    for i in range(0, len(samples)):
        if samples[i] > threshold or samples[i] < -threshold:
            results.append(samples[i])
    return results

data = [1, 8, -9, 3, 6]
data[0] = 100

try:
    out = process(data, threshold=5)
    print(out)
except IndexError:
    print("bad index")
except:
    print('something wrong')
process([1,2,3], threshold=0)

    

[100, 8, -9, 6]


[100, 8, -9, 6, 1, 2, 3]

In [8]:
def analyze(signal, window) :
    windowsum = 0
    moving_average = []
    peak_indices = []
    if len(signal) < window:
        raise ValueError(f"window ({window}) larger than signal length ({len(signal)})")
    for i in range(window):
        windowsum += signal[i]
    moving_average.append(windowsum/window)
    start = 0
    end = window
    while end < len(signal) :
        windowsum  = windowsum - signal[start] + signal[end]
        start += 1
        end += 1
        moving_average.append(windowsum/window)
    j = 1
    while j < len(signal) -1 :
        if signal[j] > signal[j-1] and signal[j] > signal[j+1]:
            peak_indices.append(j)
        j += 1
   

    return moving_average, peak_indices
signal = [2, 4, 1, 5, 9, 3, 7, 2, 8, 6]
a, b = analyze(signal, window = 3)
print(f"Moving average : {a} and Peak Indices : {b}")
    
    

    
        

Moving average : [2.3333333333333335, 3.3333333333333335, 5.0, 5.666666666666667, 6.333333333333333, 4.0, 5.666666666666667, 5.333333333333333] and Peak Indices : [1, 4, 6, 8]


In [ ]:
import math

print(math.sin(0)) # 0
print(math.sin(math.pi))     #close to 0 but a bit bigger    # careful — floating point, not exactly what you'd guess symbolically
print(math.cos(math.pi)) #exactly -1 , cause pi e cos er rate of change slow, sin pi = 0 tai
print(round(math.sqrt(2), 4)) #1.4142
print(math.floor(-3.2), math.ceil(-3.2)) #-4, -3

0.0
1.2246467991473532e-16
-1.0
1.4142
-4 -3


round() and {:0.2f}.format(number)  diye format kora jay

In [13]:
from math import sin, cos, pi

def phase_shifted(signal, shift_degrees):
    shift_rad = shift_degrees * pi / 180
    return [sin(x*pi/180 + shift_rad) for x in signal]

angles = [0, 30, 60, 90]
result = phase_shifted(angles, 90)
print(result)

[1.0, 0.8660254037844387, 0.5000000000000003, 1.2246467991473532e-16]


In [4]:
from math import sin, cos, pi
def generate_signal(freq, sample_rate, duration, waveform="sine"):
    ans = []
    x = 0
    count = duration * sample_rate
    interval = 1/sample_rate
    c = 0
    while c  < count :
       if waveform == "sine":
         ans.append( sin(x*2 * pi * freq))
       elif waveform == 'square':
         if (sin(x*2 * pi * freq) >= 0) :
            ans.append(1)
         else :
            ans.append(-1)
       else :
         raise(ValueError)
       x += interval
       c +=1
    return ans
sinew = generate_signal(5,50,0.2,"sine")
for x in sinew[:5] :
   print(f"{x:0.4f}")
sqew = generate_signal(5,50,0.2,"square")
for x in sqew[:5] :
   print(f"{x:0.4f}")
          
          


0.0000
0.5878
0.9511
0.9511
0.5878
1.0000
1.0000
1.0000
1.0000
1.0000


In [13]:
def detect_and_fix(signal, threshold):
    dict = {"pos" :0, "neg": 0, "zero" : 0}
    if len(signal) == 0:
        raise(ValueError("you are cooked"))
    for x in signal :
       if x > 0 :
           dict["pos"] += 1
       elif x < 0 :
           dict["neg"] += 1
       else :
           dict["zero"] += 1

    clipped = []
    for x in signal :
        if x > threshold:
            clipped.append(threshold)
        elif x < -threshold:
            clipped.append(-threshold)
        else :
            clipped.append(x)
    return  dict,clipped
    
signal = [3, -8, 0, 5, -2, 10, -10, 1]
print(detect_and_fix(signal,6))

({'pos': 4, 'neg': 3, 'zero': 1}, [3, -6, 0, 5, -2, 6, -6, 1])


In [5]:
import numpy as np

a = np.linspace(0, 1, 5) #()
print(a)

b = np.arange(0, 1, 0.25) #(inclusive, exclusive, step)
print(b)

print(len(a), len(b))

c = np.array([1, 2, 3])
d = np.array([10, 20, 30])
print(c + d) #[11,22,33]
print(c * 2) #[2,4,6]
print(c > 1) #[False,True,True]

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75]
5 4
[11 22 33]
[2 4 6]
[False  True  True]


In [3]:
def make_signal(t,freq):
    return np.sin(t * freq * math.pi)

In [4]:
n = np.arange(-5,6)
x1 = 3 * n - 2
x2 = np.cos(np.pi * n /4)
x3 = x1 > 0
print(x1)
print(x2)
print(x3)


[-17 -14 -11  -8  -5  -2   1   4   7  10  13]
[-7.07106781e-01 -1.00000000e+00 -7.07106781e-01  6.12323400e-17
  7.07106781e-01  1.00000000e+00  7.07106781e-01  6.12323400e-17
 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01]
[False False False False False False  True  True  True  True  True]


In [18]:
import numpy as np

t = np.linspace(-5, 5, 11)
mask = (t >= -2) & (t <= 3)
#print(mask)
#print(t)
print(t[mask]) # -2 theke 3 porjonto true just

y = np.zeros_like(t)
y[mask] = t[mask] ** 2
print(y) # -2 to 3 te thakbe eder squared value and bakigula 0

z = np.ones(11) * 10
neg_mask = t < 0
z[neg_mask] = -1 # only first 5 tay -1 hobe bakigula 10
print(z)

[-2. -1.  0.  1.  2.  3.]
[0. 0. 0. 4. 1. 0. 1. 4. 9. 0. 0.]
[-1. -1. -1. -1. -1. 10. 10. 10. 10. 10. 10.]


You can combine conditions with & (and) / | (or) — not and/or, those don't work elementwise on arrays and will raise an error. Each condition needs its own parentheses: (t > -1) & (t < 1).

In [11]:
t = np.linspace(-4, 4, 9)
y = np.zeros_like(t)
mask = (t > -1) & (t < 1)
y[mask] = 1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [17]:
t = np.linspace(-3,3,13) #13-1 = 12 diye bhag
x = np.zeros_like(t)
mask = (t >= -1) & (t <= 1)
x[mask] = 1 - abs(t[mask])
mask2 = t > 1
x[mask2] = 0.5
print(x)

[0.  0.  0.  0.  0.  0.5 1.  0.5 0.  0.5 0.5 0.5 0.5]


In [19]:
import numpy as np

t = np.linspace(-2, 2, 5)
x = t ** 2 + t          # NOT symmetric — has both even and odd behavior mixed in

x_rev = x[::-1]
print(x)
print(x_rev)

xe = (x + x_rev) / 2
xo = (x - x_rev) / 2
print(xe)
print(xo)

[2. 0. 0. 2. 6.]
[6. 2. 0. 0. 2.]
[4. 1. 0. 1. 4.]
[-2. -1.  0.  1.  2.]


In [21]:
def time_reverse(x: np.ndarray) -> np.ndarray:
    return x[::-1]

def even_odd_decompose(x: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    xe = (x + time_reverse(x)) / 2
    xo = (x - time_reverse(x)) / 2
    return xe, xo

In [22]:
import numpy as np

t_original = np.array([0.0, 2.0, 4.0, 6.0, 8.0])
x_original = np.array([0, 10, 20, 30, 40])
dt = 2.0

t_query = np.array([1.0, 5.0, 7.0])

idx_float = (t_query - t_original[0]) / dt
print(idx_float)

i_left = np.floor(idx_float).astype(int)
i_right = i_left + 1
print(i_left, i_right)

result = (x_original[i_left] + x_original[i_right]) / 2
print(result)

[0.5 2.5 3.5]
[0 2 3] [1 3 4]
[ 5. 25. 35.]


.astype(int) call, since a plain np.floor() result can't index an array.