In [1]:
import numpy as np

In [8]:
x = np.array([1,2,3,4,5,5])

In [3]:
x == 5

array([False, False, False, False,  True,  True])

In [8]:
print(np.where(x == 5)[0][1])

5


In [13]:
mask1 = (x >= 3) & (x <= 4)
print(mask1)
x[mask1]

[False False  True  True False False]


array([3, 4])

In [14]:
y = np.array([1,1,3,3,3,3])


In [15]:
y[mask1]

array([3, 3])

In [19]:
x[mask1] = [1,2]

In [17]:
print(x)

[1 2 1 2 5 5]


In [22]:
x = [1,2,3,4,5,6]
y = [1,2.000,3,4.000,5,6]
print(np.allclose(x,y))

True
