In [2]:
import numpy as np
nparr = np.array([1,2,3,4,5,6])
nparr2 = nparr.reshape((2,3))
print(nparr)
print(nparr2)
nparr2[1][2] = 9
print(nparr)
print(nparr2)
#just view ta change kore, tai jekono ta modify korle both reflect korbe


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 9]
[[1 2 3]
 [4 5 9]]


In [ ]:
nparr3 = nparr2.transpose()
print(nparr2)
print(nparr3)
nparr3[2][1] = 10
print(nparr2)
print(nparr3)
#changes in both places


[[1 2 3]
 [4 5 9]]
[[1 4]
 [2 5]
 [3 9]]
[[ 1  2  3]
 [ 4  5 10]]
[[ 1  4]
 [ 2  5]
 [ 3 10]]


In [ ]:
nparr4 = nparr[1:4]
nparr4[0] = 11
nparr
#splicing also is just a view


array([ 1, 11,  3,  4,  5, 10])

In [ ]:
nparr5 = np.sort(nparr)
print(nparr5)
print(nparr)
#two different arrays


[ 1  3  4  5 10 11]
[ 1 11  3  4  5 10]


In [ ]:
nparr6 = [3,4,99, 100]
nparr7 = np.concatenate((nparr, nparr6)) #etao alada copy toiri kore, not view
nparr7

array([  1,  11,   3,   4,   5,  10,   3,   4,  99, 100])

In [11]:
nparr7[0] = 998
nparr

array([ 1, 11,  3,  4,  5, 10])

In [3]:
nparr[nparr % 2 == 0]

array([2, 4])

In [ ]:
x = np.arange(1,25,1).reshape(2,12) #(including, excluding)
x
np.hsplit(x,3) #ekdom equally split kora jaite hobe



[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [21]:
a1 = np.array([1,2,3,4,5,6]).reshape(2,3)
a2 = np.arange(12,24,1).reshape(4,3)
a3 = np.vstack((a1,a2))
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [18]:
a2 = a2 = np.arange(12,24,1).reshape(2,6)
a3 = np.hstack((a1,a2))

In [20]:
a5, a6 = np.vsplit(a3,2)
a5

array([[ 1,  2,  3, 12, 13, 14, 15, 16, 17]])

In [27]:
a1 = a1.reshape(6,)


In [28]:
np.array_split(a1,[2,4])

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
import numpy as np
arrex = np.random.uniform(1,100, 25)

In [9]:
arrex = arrex.reshape((5,5))
arrex

array([[42.03448113, 98.08522838, 55.50920273, 52.00255019, 20.43601111],
       [40.94731374, 75.75721203, 39.40345368, 18.81618342, 83.82241312],
       [10.99955077,  6.35650274, 36.05301371,  9.1416012 , 56.58372303],
       [74.50677864, 49.98342923, 26.36973336, 43.18041072, 48.63063121],
       [27.07927678, 66.69148235, 44.20054817, 31.80599458, 32.8975527 ]])

In [10]:
np.split(arrex,5,axis = 0)


[array([[42.03448113, 98.08522838, 55.50920273, 52.00255019, 20.43601111]]),
 array([[40.94731374, 75.75721203, 39.40345368, 18.81618342, 83.82241312]]),
 array([[10.99955077,  6.35650274, 36.05301371,  9.1416012 , 56.58372303]]),
 array([[74.50677864, 49.98342923, 26.36973336, 43.18041072, 48.63063121]]),
 array([[27.07927678, 66.69148235, 44.20054817, 31.80599458, 32.8975527 ]])]

In [11]:
np.split(arrex, 5, axis = 1)

[array([[42.03448113],
        [40.94731374],
        [10.99955077],
        [74.50677864],
        [27.07927678]]),
 array([[98.08522838],
        [75.75721203],
        [ 6.35650274],
        [49.98342923],
        [66.69148235]]),
 array([[55.50920273],
        [39.40345368],
        [36.05301371],
        [26.36973336],
        [44.20054817]]),
 array([[52.00255019],
        [18.81618342],
        [ 9.1416012 ],
        [43.18041072],
        [31.80599458]]),
 array([[20.43601111],
        [83.82241312],
        [56.58372303],
        [48.63063121],
        [32.8975527 ]])]

In [22]:
aggarr = np.linspace(1,50,24)
aggarr1 = aggarr.reshape((4,6))
aggarr2 = aggarr.reshape((6,4))


In [23]:
aggarr1

array([[ 1.        ,  3.13043478,  5.26086957,  7.39130435,  9.52173913,
        11.65217391],
       [13.7826087 , 15.91304348, 18.04347826, 20.17391304, 22.30434783,
        24.43478261],
       [26.56521739, 28.69565217, 30.82608696, 32.95652174, 35.08695652,
        37.2173913 ],
       [39.34782609, 41.47826087, 43.60869565, 45.73913043, 47.86956522,
        50.        ]])

In [25]:
np.std(aggarr1, axis = 0)

array([14.29139099, 14.29139099, 14.29139099, 14.29139099, 14.29139099,
       14.29139099])

In [28]:
np.std(aggarr1, axis = 1, keepdims = True) #it changes the shape, column vector na rekhe row vector banaye dey

array([[3.63841005],
       [3.63841005],
       [3.63841005],
       [3.63841005]])

In [29]:
aggarr2

array([[ 1.        ,  3.13043478,  5.26086957,  7.39130435],
       [ 9.52173913, 11.65217391, 13.7826087 , 15.91304348],
       [18.04347826, 20.17391304, 22.30434783, 24.43478261],
       [26.56521739, 28.69565217, 30.82608696, 32.95652174],
       [35.08695652, 37.2173913 , 39.34782609, 41.47826087],
       [43.60869565, 45.73913043, 47.86956522, 50.        ]])

In [30]:
ar2 = np.array([1,2,3,4])
aggarr2 * ar2

array([[  1.        ,   6.26086957,  15.7826087 ,  29.56521739],
       [  9.52173913,  23.30434783,  41.34782609,  63.65217391],
       [ 18.04347826,  40.34782609,  66.91304348,  97.73913043],
       [ 26.56521739,  57.39130435,  92.47826087, 131.82608696],
       [ 35.08695652,  74.43478261, 118.04347826, 165.91304348],
       [ 43.60869565,  91.47826087, 143.60869565, 200.        ]])

In [32]:
ar2 = ar2.reshape(1,4)
ar2

array([[1, 2, 3, 4]])

In [33]:
aggarr2 * ar2

array([[  1.        ,   6.26086957,  15.7826087 ,  29.56521739],
       [  9.52173913,  23.30434783,  41.34782609,  63.65217391],
       [ 18.04347826,  40.34782609,  66.91304348,  97.73913043],
       [ 26.56521739,  57.39130435,  92.47826087, 131.82608696],
       [ 35.08695652,  74.43478261, 118.04347826, 165.91304348],
       [ 43.60869565,  91.47826087, 143.60869565, 200.        ]])

In [34]:
a = np.array([11,11,12,13,14,15,16,16,17,17,18,19,19,50,14,15])
a

array([11, 11, 12, 13, 14, 15, 16, 16, 17, 17, 18, 19, 19, 50, 14, 15])

In [35]:
unara, freqofara = np.unique(a, return_counts = True)
unara

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 50])

In [36]:
freqofara

array([2, 1, 1, 2, 2, 2, 2, 1, 2, 1])

In [41]:
result = np.concatenate((unara,freqofara))
result = result.reshape(2,10)
result = result.transpose()
result

array([[11,  2],
       [12,  1],
       [13,  1],
       [14,  2],
       [15,  2],
       [16,  2],
       [17,  2],
       [18,  1],
       [19,  2],
       [50,  1]])

In [48]:
unara = unara.reshape(1,unara.size)
freqofara = freqofara.reshape(1,freqofara.size)
result = np.concatenate((unara, freqofara), axis = 0)
result.transpose()


array([[11,  2],
       [12,  1],
       [13,  1],
       [14,  2],
       [15,  2],
       [16,  2],
       [17,  2],
       [18,  1],
       [19,  2],
       [50,  1]])

In [ ]:
np.sin(2)
np.cos(2)
np.tan(2)
np.arcsin(1) #in radian
np.log(2)
np.log10(20)
np.power(2,3)
np.sqrt(5)
np.pi
np.exp(2) #e^2
np.abs(-4)
#round, floor, ceil ache
np.clip(12, -10,10) #min and max value to clip kore dey

np.int64(10)